return {
	PlaceObj('ModItemCode', {
		'name', "Armor",
		'CodeFileName', "Code/Armor.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "Compatibility",
		'CodeFileName', "Code/Compatibility.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "Cfg",
		'CodeFileName', "Code/Cfg.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "Main",
		'CodeFileName', "Code/Main.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "Settings",
		'CodeFileName', "Code/Settings.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "Utils",
		'CodeFileName', "Code/Utils.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "Weapon",
		'CodeFileName', "Code/Weapon.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "WeaponComponents",
		'CodeFileName', "Code/WeaponComponents.lua",
	}),
	PlaceObj('ModItemOptionToggle', {
		'name', "ReplaceWeapons",
		'DisplayName', "Replace Weapons",
		'Help', "When enabled, replaces orginal enemy weapons with new ones",
		'DefaultValue', true,
	}),
	PlaceObj('ModItemOptionToggle', {
		'name', "ReplaceArmor",
		'DisplayName', "Replace Armor",
		'Help', "When enabled, replaces orginal enemy armor with new ones",
		'DefaultValue', true,
	}),
	PlaceObj('ModItemOptionToggle', {
		'name', "ExtraHandgun",
		'DisplayName', "Extra Handgun",
		'Help', "When enabled, gives enemies a handgun in an empty weapon slot",
		'DefaultValue', true,
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "ExtraGrenadesCount",
		'DisplayName', "Extra Grenades Count",
		'Help', "When enabled, gives enemies a grenades in an empty weapon slot",
		'DefaultValue', "2",
		'ChoiceList', {
			"0",
			"1",
			"2",
			"3",
			"4",
			"5",
			"6",
			"7",
			"8",
			"9",
			"10",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "ExtraGrenadesChance",
		'DisplayName', "Extra Grenades Chance",
		'Help', "Percentage chance to give enemies extra granades",
		'DefaultValue', "50",
		'ChoiceList', {
			"0",
			"10",
			"20",
			"30",
			"40",
			"50",
			"60",
			"70",
			"80",
			"90",
			"100",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "ArmamentStrengthFactor",
		'DisplayName', "Armament Strength Factor",
		'Help', "Alters strength of distributed Armament",
		'DefaultValue', "0",
		'ChoiceList', {
			"-10",
			"-9",
			"-8",
			"-7",
			"-6",
			"-5",
			"-4",
			"-3",
			"-2",
			"-1",
			"0",
			"1",
			"2",
			"3",
			"4",
			"5",
			"6",
			"7",
			"8",
			"9",
			"10",
		},
	}),
	PlaceObj('ModItemOptionToggle', {
		'name', "AllowAlternativeWeaponType",
		'DisplayName', "Allow Alternative Weapon Type",
		'Help', "When enabled, gives enemies chance of upgrading Handguns to SMGs and SMGs to ARs",
		'DefaultValue', true,
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "GrenadesDropChance",
		'DisplayName', "Grenades Drop Chance",
		'Help', "Percentage drop chance of grenades gnerated by C-UAE. Base game is 5 percentage, set to match your other drop mod configuration. All other items other then grenades have proper drop chance that willl inharate from base game or your mod of choice.",
		'DefaultValue', "5",
		'ChoiceList', {
			"0",
			"5",
			"10",
			"15",
			"20",
			"25",
			"30",
			"35",
			"40",
			"45",
			"50",
			"55",
			"60",
			"65",
			"70",
			"75",
			"80",
			"85",
			"90",
			"95",
			"100",
		},
	}),
	PlaceObj('ModItemOptionToggle', {
		'name', "Debug",
		'DisplayName', "Enable debug messages",
		'Help', "When enabled, prints debug logs in the game log file",
	}),
}