return PlaceObj('ModDef', {
	'title', "Cross-Mod Universal Armament Expansion",
	'description', "[h1]Cross-Mod Universal Armament  Expansion (C-UAE)[/h1]\n\n---------------\n\n[h2]What does it do[/h2]\n\nIncrease the variety of [b]Weapons[/b] and [b]Armor[/b] of all enemies you meet.\n\nThe goal of this modification is to be [b]compatible[/b] with other modifications out of the box without the requirement of compatibility patches. So mods like ToG, Rato's Gameplay Balance and Overhaul, or Tactical AI can be used with no issues.\n\n[h2]Featuers:[/h2]\n[list]\n    [*][b]Enemies get new weapon and armor of similar strength[/b]\n    [*][b]Weapons and Armor from other modifications are automatically added to pool of avaiable wepons[/b](e.g. Tons of Guns or Masters of War)\n    [*][b]Works with old saves, can be disabled at anypoint[/b]\n    [*][b][Configuration option] Strength of new armaments can be adjusted[/b]\n    [*][b]Weapons are granted attachements matching adjusted streangth[/b]\n    [*][b]Armaments condition (how much they are damaged) matches the condition of orginal loadout[/b]\n    [*][b]Mod uses drop chnace logic from base game[/b](Most mods that modife drop chnace are compatible)\n    [*][b][Configuration option] Enemies get extra Handgun[/b](Usefull for integration with mods that change Handgun logic e.g. Rato's Overhaul)\n    [*][b][Configuration option] Enemies get extra Grenades[/b]\n    [*][b]Night granades(flares etc) are only distributed during a night and in underground sectors[/b]\n    [*][b]Heavy Weapons are distributed based on ammunition type[/b](RocketMan still shoots rockets, Montar Enemy still use Montar-like weapons)\n    [*][b]Mod does not affect unique armaments[/b](e.g.[spoiler] Pieree won't lose his unique machete [/spoiler])\n[/list]\n\n---------------\n\n[h2]Recommended mods[/h2]\n[list]\n    [*][b][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3090261695] Masters of War [/url][/b] Note: Random Enemy Weapons is required for Masters of War to load but can be disabled\n    [*][b][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3023672178] Tons of Guns [/url][/b]\n[/list]\n\n---------------\n\n[h2]How does it do[/h2]\nWhenever players enter a sector all enemies are scanned and a profile of their [b]level[/b], [b]affiliation[/b], and [b]loadout[/b] is created. This profile then is used to generate new weapons and armor. Mod uses [b]Cost[/b] property of items to access the items of similar strength.\n\n[h3]Avaiable Armaments Logic[/h3]\nC-UAE is build based on in game system of Cost and Bobby Ray's CanAppearInShop property. So only armaments that can appear in the shop are distributed to enemies.\n\nThis way mod automatically filters out all left over, unfinised or quest items. Unfinised and test items can be found in both the Vanilla game as well as in some popular weapon mods.\n\n[h3]Weapons[/h3]\nNew weapons are generated of the same type. Based on the enemy level, affiliation, and the cost of the original weapon, the mod finds the proper weapon cost range and gives a random weapon from that range.\n\nNew weapons are also granted Components/Weapons' Mods (e.g. Scopes or Silencer) based on enemy level and affiliation.\n\nAdditionally, if the original loadout has free spots left and there was no Handgun or Grenade then the enemy might get an extra Handgun or Grenade.\n\n[h3]Armor[/h3]\nArmor follows a similar logic to weapons. Based on the enemy level, affiliation, and original armor new armor is spawned.\n\n[h3]Uniques[/h3]\nEnemies can't get unique weapons like Golden Gun. But also enemies who wield unique weapons or armor will keep them. For exmaple enemeis with \"Shiny and Chrome Helmet\" will keep it but thier weapon and other armor pieces will get replace acording to the mod logic.\n\n---------------\n\n[h2]Configuration options[/h2]\n[list]\n    [*][b]Extra Handgun[/b] If the original loadout has free spots left and there is no Handgun the enemy will get an extra Handgun.\n    [*][b]Extra Grenades Count[/b] If the original loadout has free spots left and there is no Grenade the enemy will get an extra Grenade of this count. Setting it to 0 causes no extra grenades.\n    [*][b]Extra Grenades Chance[/b] modifies the chance an enemy will get extra granades.\n    [*][b]Armament Strength Factor[/b] dificulty adjustement. Negative values cause the cost range to be closer to the cheapest armaments. Positive values make the cost range to be closer to expensive armaments. Note: orginal loadout is always within the cost range.\n    [*][b]Allow Alternative Weapon Type[/b] alternative version of weapon generation. Handguns can randomly be upgraded to SMGs, SMGs to ARs, and ARs to LMG or Sniper Rifles. \n[/list]\n\n---------------\n\n[h2]Special compatibility options for modders[/h2]\n\nAfter discussing with fellow modders I decied to add to C-UAE two entrypoints desingned to support special compatibility cases. Read more in the [b]Discussions[/b] section.\n\n---------------\n\n[h2]Notes[/h2]\n[list]\n    [*][b]Compatible[/b] with all weapon mods and new enemies mods as loong as they support Bobby Ray's\n    [*]Mod uses enemy level as a base therefore it is affected by difficulty and can be more adjusted by using my other mod [b]Adjust Difficulty Settings[/b]\n    [*]Can be enabled and disabled at any point\n    [*]Works with all saves. Will not change enemies in the middle of a fight.\n    [*]No compatible with Random Enemy Weapons as it duplicates its features\n    [*]Source code is available at [url=https://github.com/lucekdudek/C-UAE]GitHub[/url]\n[/list]\n\n---------------\n\n[h2]Bugs and limitations[/h2]\n[list]\n    [*]The drop chance of grenades is hardcoded to match the original drop chance of 5% therefore drop chance mods won't affect how often grenades are being dropped\n    [*]Dose not work with [url=https://steamcommunity.com/sharedfiles/filedetails/?id=3027443738]New weapons of combinations of the original model[/url] as it was not updated to work with Bobby Ray's update\n[/list]",
	'image', "Mod/LDCUAE/Images/Preview.png",
	'last_changes', "Improve Mod Options are being loaded",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"*.code-workspace/*",
	},
	'id', "LDCUAE",
	'author', "Lucjan",
	'version_major', 2,
	'version_minor', 3,
	'version', 56,
	'lua_revision', 233360,
	'saved_with_revision', 349542,
	'code', {
		"Code/Armor.lua",
		"Code/Compatibility.lua",
		"Code/Cfg.lua",
		"Code/Main.lua",
		"Code/Settings.lua",
		"Code/Utils.lua",
		"Code/Weapon.lua",
		"Code/WeaponComponents.lua",
	},
	'default_options', {
		AllowAlternativeWeaponType = true,
		ArmamentStrengthFactor = "0",
		Debug = false,
		ExtraGrenadesChance = "50",
		ExtraGrenadesCount = "2",
		ExtraHandgun = true,
	},
	'saved', 1706739510,
	'code_hash', -2100659557822958352,
	'affected_resources', {},
	'steam_id', "3148282483",
	'TagWeapons&Items', true,
	'TagEnemies', true,
	'TagGameSettings', true,
})