return PlaceObj('ModDef', {
	'title', "C-UAE Cross-Mod Universal Armament Expansion",
	'description', "[h1]Cross-Mod Universal Armament Expansion (C-UAE)[/h1]\n\nTL;DR\n\nSemi-Random Enemy Weapons and Enemy Armor with a robust weapon attachment and ammo distribution system that scales with campaign progression. Designed to support other mods.\n\n[h2]To [b]Tactical AI Project[/b] users[/h2]\n\nIf you dislike random weapons and want to retain the feeling of vanilla weapon progression, disable that in the mod options. C-UAE will still upgrade enemies' weapons according to Tactical AI logic (enemies will always have access to grenades, a handgun, and a non-handgun main weapon).\n\n[h2]What does it do[/h2]\n\nIncrease the variety of [b]Weapons[/b] and [b]Armor[/b] of all enemies you encounter.\n\nThe goal of this mod is to be [b]compatible[/b] with other mods out of the box without requiring compatibility patches. Mods like ToG, Rato's Overhaul, or AI mods can be used without issues.\n\n[h2]Features:[/h2]\n[list]\n    [*][b]Enemies receive new weapons and armor of similar strength[/b]\n    [*][b]Weapons and Armor from other mods are automatically added to the pool[/b] (e.g., Tons of Guns or Masters of War)\n    [*][b]Robust attachment system. Weapons are granted attachments matching adjusted enemy level. At higher levels, enemies will have more powerful attachments[/b]\n    [*][b]Ammunition distribution system. At higher levels, enemies will have increasingly powerful ammunition[/b]\n    [*][b]Works with old saves and can be disabled at any point[/b]\n    [*][b]Armaments' condition (how damaged they are) matches the original loadout[/b]\n    [*][b]Mod uses base game drop chance logic[/b] (Most mods altering drop chance are compatible)\n    [*][b]Night grenades (flares, etc.) are only distributed during nighttime and in underground sectors[/b]\n    [*][b]Heavy Weapons are distributed based on ammunition type[/b] (RocketMen still shoot rockets; Montar enemies still use mortar-like weapons)\n    [*][b]Mod does not affect unique armaments[/b] (e.g., [spoiler]Pierre won't lose his unique machete[/spoiler])\n[/list]\n\n[h2]C-UAE vs Random Enemy Weapons[/h2]\n\n[b]C-UAE[/b] distributes all available weapons across all enemy factions, while [b]REW[/b] uses structured distribution with handpicked weapons for specific factions. This means modded weapons not configured for REW won’t be distributed, whereas C-UAE excludes weapons unavailable at Bobby Ray’s.\n\n[b]Configuration options[/b] allow disabling weapon replacement, enabling players to use [b]REW[/b] weapon logic alongside other C-UAE features.\n\n[h2]Recommended mods to use with C-UAE[/h2]\n\n[b]More Armaments[/b]\n\n[list]\n    [*][b][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3157842808]More Armor[/url][/b] Note: New vanilla armor and variations of existing ones\n    [*][b][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3023672178]Tons of Guns[/url][/b] Note: New weapons\n    [*][b][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3090261695]Masters of War[/url][/b] Note: New weapons\n[/list]\n\n[b]Enemy AI[/b]\n\n[list]\n    [*][b][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3411008594]Rato's AI Overhaul[/url][/b]\n    [*][b][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3042581131]Tactical AI Project (Old The Grand Chien Nightmare)[/url][/b]\n[/list]\n\n[b]Alternative Balance (Alongside More Armaments)[/b]\n\n[list]\n    [*][b][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3021320057]Rato's Gameplay Balance and Overhaul 3[/url][/b] Note: New weapon logic\n    [*][b][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3229507332]Enemy Armors[/url][/b] Note: Better-armored enemies\n    [*][b][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3038472406]BCE Guns[/url][/b] and [b][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3031643676]Armor Crafting Economy[/url][/b] Note: New weapons/armor; incompatible with other mods\n[/list]\n\nNote: [b]BCE[/b] alters vanilla weapon prices and is unbalanced for vanilla economies, conflicting with ToG/MoW.\n\nAvoid using all listed mods together. Check individual mod descriptions for compatibility.\n\n[h2]How does it work?[/h2]\nWhen encountering enemies in satellite or tactical view, the mod scans their [b]level[/b], [b]faction[/b], and [b]loadout[/b] to generate a profile. This profile creates new weapons/armor. The mod tracks modified enemies to avoid reprocessing them later.\n\n[h3]Available Armaments Logic[/h3]\nC-UAE uses in-game [b]Cost[/b] and Bobby Ray’s [b]CanAppearInShop[/b] property. Only shop-available armaments are distributed (excluding manually integrated mods), filtering out quest/unfinished items from vanilla or mods.\n\n[h3]Weapons[/h3]\nNew weapons match the original’s type, enemy level, faction, and cost range. Attachments (scopes, silencers) are added based on enemy level.\n\n[h3]Armor[/h3]\nArmor follows similar logic, replacing pieces while considering enemy level, faction, and original armor.\n\n[h3]Uniques[/h3]\nUnique weapons/armor (e.g., Golden Gun, Shiny and Chrome Helmet) are retained. Only non-unique items are replaced.\n\n[h2]Modder Compatibility Options[/h2]\n\nDetails in the [b]Discussions[/b] section.\n\n[h2]Notes[/h2]\n[list]\n    [*]Enemies won’t change mid-combat.\n    [*]Source code: [url=https://github.com/lucekdudek/C-UAE]GitHub[/url]\n[/list]",
	'image', "Mod/LDCUAE/Images/Preview.png",
	'last_changes', "Fixed potential issue with missing weapons when new weapon is of bigger size",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"*.code-workspace/*",
		"local/*",
	},
	'id', "LDCUAE",
	'author', "Lucjan",
	'version_major', 4,
	'version_minor', 2,
	'version', 130,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"Code/Ammo.lua",
		"Code/Armor.lua",
		"Code/Compatibility.lua",
		"Code/Cfg.lua",
		"Code/Loadout.lua",
		"Code/Logger.lua",
		"Code/Main.lua",
		"Code/Settings.lua",
		"Code/Test.lua",
		"Code/Utils.lua",
		"Code/Weapon.lua",
		"Code/WeaponComponents.lua",
	},
	'default_options', {
		AddWeaponComponents = true,
		AffectMilitia = true,
		ArmamentStrengthFactor = "0",
		ReplaceArmor = true,
		ReplaceWeapons = true,
	},
	'saved', 1738267150,
	'code_hash', -182358022787815048,
	'affected_resources', {},
	'steam_id', "3148282483",
	'TagBalancing&Difficulty', true,
	'TagEnemies', true,
	'TagGameSettings', true,
	'TagWeapons&Items', true,
})