Cuae_LoadedModOptions = {
	-- visible options
	ReplaceWeapons = true,
	AddWeaponComponents = true,
	ReplaceArmor = true,
	AffectMilitia = true,
	ArmamentStrengthFactor = 0,
	-- hidden options
	DisallowSilencers = true,
	ApplyChangesInSateliteView = true,
	LoadoutTables = nil,
	-- legacy options for Tactical AI Project
	LegacyLoadoutTable = nil,
	ExtraGrenadesCount = 0,
	ExtraHandgun = false,
	AlternativeWeaponTypeTables = nil,
	-- top secret options - only accessible when passed directly to Cuae_ChangeArmament
	AlwaysAddArmor = false,
}

Cuae_ForcedOptions = {}

Cuae_AffiliationExclusionTable = {}

Cuae_ImmunityTable = {
	-- Quest and personal
	TheThing = true,
	PierreMachete = true,
	EndlessKnives = true,
	GutHookKnife = true,
	Galil_FlagHill = true,
	LionRoar = true,
	Auto5_quest = true,
	TexRevolver = true,
	GoldenGun = true,
	Winchester_Quest = true,
	ShamanLeggings = true,
	ShamanHelmet = true,
	ShamanTorso = true,
	NailsLeatherVest = true,
	IvanUshanka = true,
	Machete_Crafted = true,
	ShapedCharge = true,
	-- Specific vanilla helmet
	PostApoHelmet = true,
	-- U-Bahn DLC
	Gasmaskenhelm = true,
	-- Task-oriented head pieces
	GasMask = true,
	NightVisionGoggles = true,
}

Cuae_AffiliationWeight = {
	Rebel = 0,
	Legion = -1,
	Thugs = 0,
	Army = 0,
	Adonis = 1,
	SuperSoldiers = 0,
	Militia = 1,
}

-- Position in table corresponds with a adjusted unit level 1...20
Cuae_UnitLevelToComponentChance = {
	18,
	24,
	30,
	36,
	42,
	48,
	54,
	60,
	66,
	72,
	78,
	84,
	90,
	92,
	94,
	95,
	96,
	97,
	98,
	99,
}

Cuae_ExcludeWeapons = {
	-- ToG OP
	"Katana_1",
	-- ToG outdated/broken
	"MK23_1",
	"Fn2000_1",
	"B93R_1",
	"G3_1",
	-- Grenade
	"ConcussiveGrenade_Mine",
	"ShapedCharge",
	"Super_HE_Grenade",
	-- Task-oriented head pieces
	"GasMask",
	"NightVisionGoggles",
}

Cuae_Whitelist = {
	-- ToG
	-- Handgun
	"Mauser_C96_1",
	"C96R_1",
	-- SMG
	"PPSh41_1",
	-- AR
	"AR10_worn",
	"AR10commando_worn",
	"G3A3_1",
	"M70D_1",
	"STG44R_1",
	-- Sniper
	"Gewehr43_1",
	"M1Garand_5",
	"SKS_1",
	"Type56C_1",
	"Type56D_1",
	-- MachineGun
	"BrenMKI_1",
	"HK23ECamo_1",
	"M1918A2_1",
	"Mac24_1",
	"U100C_1",
	-- More Armor
	"CamoFlakArmor",
	"CamoFlakArmor_CeramicPlates",
	"CamoFlakArmor_WeavePadding",
	"CamoFlakVest_CeramicPlates",
	"CamoFlakVest_WeavePadding",
	"CamoKevlarChestplate",
	"CamoKevlarChestplate_CeramicPlates",
	"CamoKevlarChestplate_WeavePadding",
	"CamoKevlarVest_CeramicPlates",
	"CamoKevlarVest_WeavePadding",
	"RedCamoFlakArmor",
	"RedCamoFlakArmor_CeramicPlates",
	"RedCamoFlakArmor_WeavePadding",
	"RedCamoFlakVest",
	"RedCamoFlakVest_CeramicPlates",
	"RedCamoFlakVest_WeavePadding",
	"RedCamoKevlarChestplate",
	"RedCamoKevlarChestplate_CeramicPlates",
	"RedCamoKevlarChestplate_WeavePadding",
	"RedCamoKevlarVest",
	"RedCamoKevlarVest_CeramicPlates",
	"RedCamoKevlarVest_WeavePadding",
	"RedFlakArmor",
	"RedFlakArmor_CeramicPlates",
	"RedFlakArmor_WeavePadding",
	"RedFlakLeggings",
	"RedFlakLeggings_WeavePadding",
	"RedFlakVest",
	"RedFlakVest_CeramicPlates",
	"RedFlakVest_WeavePadding",
	"RedHeavyArmorChestplate",
	"RedHeavyArmorChestplate_CeramicPlates",
	"RedHeavyArmorChestplate_WeavePadding",
	"RedHeavyArmorHelmet",
	"RedHeavyArmorHelmet_WeavePadding",
	"RedHeavyArmorLeggings",
	"RedHeavyArmorLeggings_WeavePadding",
	"RedHeavyArmorTorso",
	"RedHeavyArmorTorso_CeramicPlates",
	"RedHeavyArmorTorso_WeavePadding",
	"RedKevlarChestplate",
	"RedKevlarChestplate_CeramicPlates",
	"RedKevlarChestplate_WeavePadding",
	"RedKevlarHelmet",
	"RedKevlarHelmet_WeavePadding",
	"RedKevlarLeggings",
	"RedKevlarLeggings_WeavePadding",
	"RedKevlarVest",
	"RedKevlarVest_CeramicPlates",
	"RedKevlarVest_WeavePadding",
	"RedLightHelmet",
	"RedLightHelmet_WeavePadding",
	"YellowFlakArmor",
	"YellowFlakArmor_CeramicPlates",
	"YellowFlakArmor_WeavePadding",
	"YellowFlakLeggings",
	"YellowFlakLeggings_WeavePadding",
	"YellowFlakVest",
	"YellowFlakVest_CeramicPlates",
	"YellowFlakVest_WeavePadding",
	"YellowHeavyArmorChestplate",
	"YellowHeavyArmorChestplate_CeramicPlates",
	"YellowHeavyArmorChestplate_WeavePadding",
	"YellowHeavyArmorHelmet",
	"YellowHeavyArmorHelmet_WeavePadding",
	"YellowHeavyArmorLeggings",
	"YellowHeavyArmorLeggings_WeavePadding",
	"YellowHeavyArmorTorso",
	"YellowHeavyArmorTorso_CeramicPlates",
	"YellowHeavyArmorTorso_WeavePadding",
	"YellowKevlarChestplate",
	"YellowKevlarChestplate_CeramicPlates",
	"YellowKevlarChestplate_WeavePadding",
	"YellowKevlarHelmet",
	"YellowKevlarHelmet_WeavePadding",
	"YellowKevlarLeggings",
	"YellowKevlarLeggings_WeavePadding",
	"YellowKevlarVest",
	"YellowKevlarVest_CeramicPlates",
	"YellowKevlarVest_WeavePadding",
	"YellowLightHelmet",
	"YellowLightHelmet_WeavePadding",
}

local tagsIntimateCloseQuarters = {
	Intimate = true,
	CloseQuarters = true,
}
local tagsIntimateTactical = {
	Intimate = true,
	CloseQuarters = true,
	Tactical = true,
}
local tagsIntimatePrecision = {
	Intimate = true,
	CloseQuarters = true,
	Tactical = true,
	Precision = true,
}
local tagsIntimateStrategic = {
	Intimate = true,
	CloseQuarters = true,
	Tactical = true,
	Precision = true,
	Strategic = true,
}
local tagsCloseQuartersTactical = {
	CloseQuarters = true,
	Tactical = true,
}
local tagsCloseQuartersPrecision = {
	CloseQuarters = true,
	Tactical = true,
	Precision = true,
}
local tagsCloseQuartersStrategic = {
	CloseQuarters = true,
	Tactical = true,
	Precision = true,
	Strategic = true,
}
local tagsTacticalPrecision = {
	Tactical = true,
	Precision = true,
}
local tagsTacticalStrategic = {
	Tactical = true,
	Precision = true,
	Strategic = true,
}
local tagsPrecisionStrategic = {
	Precision = true,
	Strategic = true,
}

Cuae_WeaponComponentTagsCfg = {
	RAT_TOG_SteyrS_Barrel_def_555 = tagsCloseQuartersTactical,
	Condor_Mag_fed_1 = tagsCloseQuartersTactical,
	RAT_TOG_WideScope = tagsCloseQuartersTactical,
	RAT_TOG_WideScope_rpk_mount = tagsCloseQuartersTactical,
	WideScope = tagsCloseQuartersTactical,
	RAT_TOG_vigilanceRS = tagsCloseQuartersTactical,
	_ReflexSIghtVigilance = tagsCloseQuartersTactical,
	RAT_TOG_Prism_rpk_mount = tagsCloseQuartersTactical,
	ScopeCOG = tagsCloseQuartersTactical,
	RAT_TOG_Prism = tagsCloseQuartersTactical,
	RAT_TOG_Reflex = tagsCloseQuartersTactical,
	RAT_TOG_Reflex_rpk_mount = tagsCloseQuartersTactical,
	AUGScope_Default = tagsCloseQuartersTactical,
	RAT_TOG_ACOG_rpk_mount = tagsCloseQuartersTactical,
	ScopeCOGQuick = tagsCloseQuartersTactical,
	RAT_TOG_ACOG = tagsCloseQuartersTactical,
	RAT_TOG_Reflex_pistol_rpk_mount = tagsCloseQuartersTactical,
	SCOPE_G36_2 = tagsCloseQuartersTactical,
	G36_SCOPE = tagsCloseQuartersTactical,
	ReflexSight = tagsCloseQuartersTactical,
	RAT_TOG_compactRS_rpk_mount = tagsCloseQuartersTactical,
	RAT_TOG_compactRS = tagsCloseQuartersTactical,
	GW43_Scope_1 = tagsCloseQuartersTactical,
	_Master_GW43_Scope_TOG = tagsCloseQuartersTactical,
	VSK94_Pistolgrip_1 = tagsCloseQuartersTactical,
	RK95_Stock_shrt_1 = tagsCloseQuartersTactical,
	RK95_Handguard_ext_1 = tagsCloseQuartersPrecision,
	_Master_Handguard_ext_TOG = tagsCloseQuartersPrecision,
	RK62_Handguard_ext_1 = tagsCloseQuartersPrecision,
	_Master_VigM2_Stock_unfld_TOG = tagsCloseQuartersStrategic,
	BM59MK3_unfld = tagsCloseQuartersStrategic,
	FAMAE_stock_unfld_1 = tagsCloseQuartersStrategic,
	Spas12_Stock_unfold_1 = tagsCloseQuartersStrategic,
	VigM2_Stock_unfld_1 = tagsCloseQuartersStrategic,
	_Master_StockLightUnfolded_TOG = tagsCloseQuartersStrategic,
	HK53_stock_unfld_1 = tagsCloseQuartersStrategic,
	M70_stock_unfld_1 = tagsCloseQuartersStrategic,
	M70D_stock_unfld_1 = tagsCloseQuartersStrategic,
	Mac11_Stock_unfld_1 = tagsCloseQuartersStrategic,
	MP7_stock_unfld_1 = tagsCloseQuartersStrategic,
	PP91_Stock_unfld_1 = tagsCloseQuartersStrategic,
	VSK94_stock_unfld_1 = tagsCloseQuartersStrategic,
	barrel_confidante = tagsIntimateCloseQuarters,
	DuckbillChoke = tagsIntimateCloseQuarters,
	G11_Rail_8 = tagsIntimateCloseQuarters,
	stealth_ironsight_confidante = tagsIntimateCloseQuarters,
	WA2000_NoScope_1 = tagsIntimateCloseQuarters,
	RAT_TOG_vigilanceRS_rpk_mount = tagsIntimateCloseQuarters,
	MP7_Scope_1 = tagsIntimateCloseQuarters,
	TAR21_Scope_Rflx_1 = tagsIntimateCloseQuarters,
	ReflexSightAdvanced = tagsIntimateCloseQuarters,
	Caws_Scope_1 = tagsIntimateCloseQuarters,
	FlashlightDot_Anaconda = tagsIntimateCloseQuarters,
	RAT_TOG_flashlight_rpk_mount = tagsIntimateCloseQuarters,
	RAT_TOG_flashlight = tagsIntimateCloseQuarters,
	Flashlight_Anaconda = tagsIntimateCloseQuarters,
	Automag_Scope_1 = tagsIntimateCloseQuarters,
	RAT_TOG_Reflex_pistol = tagsIntimateCloseQuarters,
	ReflexSightAdvanced_Glock = tagsIntimateCloseQuarters,
	RK62_Irons_1 = tagsIntimateCloseQuarters,
	VSS_Ironsight_1 = tagsIntimateCloseQuarters,
	RK95_Irons_1 = tagsIntimateCloseQuarters,
	ImprovedIronsight = tagsIntimateCloseQuarters,
	ImprovedIronsight_AR15 = tagsIntimateCloseQuarters,
	BaseIronsight_Anaconda = tagsIntimateCloseQuarters,
	EM2_ironsight_1 = tagsIntimateCloseQuarters,
	L85A1_ironsight_1 = tagsIntimateCloseQuarters,
	LeeEn_Irons_1 = tagsIntimateCloseQuarters,
	M60_Irons_1 = tagsIntimateCloseQuarters,
	PPSh_Scope_iron_1 = tagsIntimateCloseQuarters,
	FNMD_ironsight_1 = tagsIntimateCloseQuarters,
	RPD_ironsight_1 = tagsIntimateCloseQuarters,
	MicroUZI_Scope_def_1 = tagsIntimateCloseQuarters,
	ToG_Rail_Block = tagsIntimateCloseQuarters,
	Caws_Ironsight_1 = tagsIntimateCloseQuarters,
	MP7_Ironsight_1 = tagsIntimateCloseQuarters,
	GewehrDefaultSight = tagsIntimateCloseQuarters,
	DefaultIronsight_AR15 = tagsIntimateCloseQuarters,
	FAMAE_ironsight_1 = tagsIntimateCloseQuarters,
	Mosin_Scope_iron_1 = tagsIntimateCloseQuarters,
	BM59MK3_stock = tagsIntimateCloseQuarters,
	Spas12_Stock_fold_1 = tagsIntimateCloseQuarters,
	BM59MK3_fld = tagsIntimateCloseQuarters,
	FAMAE_stock_fld_1 = tagsIntimateCloseQuarters,
	StockNo = tagsIntimateCloseQuarters,
	_Master_StockFolded_TOG = tagsIntimateCloseQuarters,
	_Master_StockNormalFolded_TOG = tagsIntimateCloseQuarters,
	AN94_Stock_fld_1 = tagsIntimateCloseQuarters,
	HK53_stock_fld_1 = tagsIntimateCloseQuarters,
	M70_stock_fld_1 = tagsIntimateCloseQuarters,
	M70D_stock_fld_1 = tagsIntimateCloseQuarters,
	Mac11_Stock_fld_1 = tagsIntimateCloseQuarters,
	MP7_stock_fld_1 = tagsIntimateCloseQuarters,
	PP91_Stock_fld_1 = tagsIntimateCloseQuarters,
	StockFolded = tagsIntimateCloseQuarters,
	VSK94_stock_fld_1 = tagsIntimateCloseQuarters,
	_Master_VigM2_Stock_fld_TOG = tagsIntimateCloseQuarters,
	VigM2_Stock_fld_1 = tagsIntimateCloseQuarters,
	NTW20_stock_fld_1 = tagsIntimateCloseQuarters,
	VigM2_Stock_hlffld_1 = tagsIntimateCloseQuarters,
	Leovision_Harpy = tagsIntimateCloseQuarters,
	Sovitron_Kentaur = tagsIntimateCloseQuarters,
	Leovision_Falcon = tagsIntimateCloseQuarters,
	Leovision_Eagle = tagsIntimateCloseQuarters,
	Silentium_Assasin = tagsIntimateCloseQuarters,
	Silentium_Basic = tagsIntimateCloseQuarters,
	Silentium_Hush = tagsIntimateCloseQuarters,
	Silentium_Basic_1 = tagsIntimateCloseQuarters,
	Silentium_Assasin_1 = tagsIntimateCloseQuarters,
	Silentium_Hush_1 = tagsIntimateCloseQuarters,
	BarrelLight_handgun = tagsIntimateTactical,
	R_TOG_light_barrel = tagsIntimateTactical,
	BarrelLight = tagsIntimateTactical,
	BarrelShort_AUG = tagsIntimateTactical,
	BarrelShortShotgun = tagsIntimateTactical,
	BarrelShort_Winchester = tagsIntimateTactical,
	BarrelShortShotgun_Benelli = tagsIntimateTactical,
	Auto5_Short_NMag = tagsIntimateTactical,
	BarrelShort_Light_handgun = tagsIntimateTactical,
	BarrelShort_Light = tagsIntimateTactical,
	B93RR_barrel_shrt_1 = tagsIntimateTactical,
	BarrelShort_handgun = tagsIntimateTactical,
	VigM2_Barrel_shrt_1 = tagsIntimateTactical,
	BarrelShortImproved_handgun = tagsIntimateTactical,
	hk33_barrel_shrt_1 = tagsIntimateTactical,
	Type56C_Barrel_shrt_1 = tagsIntimateTactical,
	AN94_Barrel_short_1 = tagsIntimateTactical,
	Type56A_Barrel_shrt_1 = tagsIntimateTactical,
	m76_barrel_shrt_1 = tagsIntimateTactical,
	BrenMK1_Barrel_shrt_1 = tagsIntimateTactical,
	Type56D_Barrel_shrt_1 = tagsIntimateTactical,
	Type56B_Barrel_shrt_1 = tagsIntimateTactical,
	hk23e_barrel_shrt_1 = tagsIntimateTactical,
	RK95_Barrel_shrt_1 = tagsIntimateTactical,
	_Master_BarrelShort = tagsIntimateTactical,
	Papovka2_Barrel_shrt_1 = tagsIntimateTactical,
	BarrelShort = tagsIntimateTactical,
	Papovka_Barrel_shrt_1 = tagsIntimateTactical,
	M70_barrel_shrt_1 = tagsIntimateTactical,
	G3A3_barrel_shrt_1 = tagsIntimateTactical,
	RK62_Barrel_shrt_1 = tagsIntimateTactical,
	M70D_barrel_shrt_1 = tagsIntimateTactical,
	STG44_Barrel_shrt_1 = tagsIntimateTactical,
	BarrelShortImproved_AUG = tagsIntimateTactical,
	BarrelShortImproved = tagsIntimateTactical,
	C96R_barrel_shrt_1 = tagsIntimateTactical,
	M48_barrel_shrt_1 = tagsIntimateTactical,
	FNMD_barrel_shrt_1 = tagsIntimateTactical,
	A91_762_barrel_shrt_1 = tagsIntimateTactical,
	L85A1_barrel_shrt_1 = tagsIntimateTactical,
	EM2_barrel_shrt_1 = tagsIntimateTactical,
	BM59_barrel_shrt = tagsIntimateTactical,
	MAC2429_barrel_shrt_1 = tagsIntimateTactical,
	M82_barrel_shrt_1 = tagsIntimateTactical,
	FAMAE_barrel_shrt_1 = tagsIntimateTactical,
	U100_Barrel_shrt_1 = tagsIntimateTactical,
	AR10_barrel_shrt = tagsIntimateTactical,
	mk23_barrel_shrt_1 = tagsIntimateTactical,
	NTW_20_barrel_ext_1 = tagsIntimateTactical,
	M1897_barrel_shrt = tagsIntimateTactical,
	Condor_Barrel_shrt_1 = tagsIntimateTactical,
	M1897_barrel_sshrt = tagsIntimateTactical,
	CondorN_Barrel_shrt_1 = tagsIntimateTactical,
	RK95_Handguard_shrt_1 = tagsIntimateTactical,
	RK62_Handguard_shrt_1 = tagsIntimateTactical,
	_Master_Handguard_short_TOG = tagsIntimateTactical,
	AK47_TacGrip = tagsIntimateTactical,
	AK47_VerticalGrip = tagsIntimateTactical,
	AKSU_VerticalGrip = tagsIntimateTactical,
	RPK74_VerticalGrip = tagsIntimateTactical,
	DefaultIronsight_M82 = tagsIntimateTactical,
	Condor_Mag_magn_1 = tagsIntimateTactical,
	M1918A2_handle_def_1 = tagsIntimateTactical,
	FNMD_Handle_1 = tagsIntimateTactical,
	U100_handle_1 = tagsIntimateTactical,
	AR10_grip_mountfront = tagsIntimateTactical,
	RAT_TOG_tactical_dot = tagsIntimateTactical,
	RAT_TOG_tactical_dot_rpk_mount = tagsIntimateTactical,
	LaserDot_Anaconda = tagsIntimateTactical,
	UVDot_Anaconda = tagsIntimateTactical,
	RAT_TOG_uv_dot_rpk_mount = tagsIntimateTactical,
	RAT_TOG_uv_dot = tagsIntimateTactical,
	RAT_TOG_laser_dot_rpk_mount = tagsIntimateTactical,
	RAT_TOG_laser_dot = tagsIntimateTactical,
	ToG_Flashlight_1 = tagsIntimateTactical,
	Flashlight = tagsIntimateTactical,
	Flashlight_PSG_M1 = tagsIntimateTactical,
	Flashlight_aa12 = tagsIntimateTactical,
	FlashlightDot_PSG_M1 = tagsIntimateTactical,
	FlashlightDot_aa12 = tagsIntimateTactical,
	FlashlightDot = tagsIntimateTactical,
	ToG_Flashlight_2 = tagsIntimateTactical,
	ToG_Flashlight_3 = tagsIntimateTactical,
	StockLight_AR_BurstOnly = tagsIntimateTactical,
	BrenMK1_Stock_shrt_1 = tagsIntimateTactical,
	DeLisle_stock_erg_1 = tagsIntimateTactical,
	hk23e_stock_erg_1 = tagsIntimateTactical,
	LeeEn_Stock_erg_1 = tagsIntimateTactical,
	M60_Stock_erg_1 = tagsIntimateTactical,
	m76_stock_erg_1 = tagsIntimateTactical,
	Papovka_Stock_erg_1 = tagsIntimateTactical,
	Papovka_Stock_erg_cross1_1 = tagsIntimateTactical,
	Papovka2_Stock_erg_1 = tagsIntimateTactical,
	Papovka2_Stock_erg_cross1_1 = tagsIntimateTactical,
	PPSh_Stock_short_1 = tagsIntimateTactical,
	RK62_Stock_shrt_1 = tagsIntimateTactical,
	STG44_Stock_erg_1 = tagsIntimateTactical,
	StockLight = tagsIntimateTactical,
	Type56A_stock_erg_1 = tagsIntimateTactical,
	Type56B_stock_erg_1 = tagsIntimateTactical,
	Type56C_stock_erg_1 = tagsIntimateTactical,
	Type56D_stock_erg_1 = tagsIntimateTactical,
	AR10_stock_erg = tagsIntimateTactical,
	EM2_stock_erg_1 = tagsIntimateTactical,
	FNMD_stock_erg_1 = tagsIntimateTactical,
	MAC2429_Stock_erg_1 = tagsIntimateTactical,
	Type56A_stock_erg_c = tagsIntimateTactical,
	Type56B_stock_erg_c = tagsIntimateTactical,
	Type56C_stock_erg_c = tagsIntimateTactical,
	Type56D_stock_erg_c = tagsIntimateTactical,
	U100_Stock_erg_1 = tagsIntimateTactical,
	VerticalGrip_AUG = tagsIntimateTactical,
	B93RR_grip_unfld_1 = tagsIntimateTactical,
	MP7_Grip_fld_1 = tagsIntimateTactical,
	B93RR_grip_fld_1 = tagsIntimateTactical,
	B93R_Under_fld_1 = tagsIntimateTactical,
	_Master_B93RR_grip_fld_TOG = tagsIntimateTactical,
	M60_Bip_fld_1 = tagsIntimatePrecision,
	hk23e_bipod_fld_1 = tagsIntimatePrecision,
	RPD_bipod_fld_1 = tagsIntimatePrecision,
	hk33_bipod_fld_1 = tagsIntimatePrecision,
	BrenMK1_Bipod_fld_1 = tagsIntimatePrecision,
	PKM_Bipod_Fold_1 = tagsIntimatePrecision,
	AR10_bipod_fld = tagsIntimatePrecision,
	NTW20_bipod_fld_1 = tagsIntimatePrecision,
	FNMD_bipod_fld_1 = tagsIntimatePrecision,
	MAC2429_Bipod_fld_1 = tagsIntimatePrecision,
	U100_bipod_fld_1 = tagsIntimatePrecision,
	BM59_bipod_fld = tagsIntimatePrecision,
	WA2000_Bipod_Fold_1 = tagsIntimatePrecision,
	Type56C_Bay_fld_1 = tagsIntimatePrecision,
	LaserDot_aa12 = tagsIntimatePrecision,
	LaserDot = tagsIntimatePrecision,
	LaserDot_PSG_M1 = tagsIntimatePrecision,
	ToG_Red_Dot_1 = tagsIntimatePrecision,
	MK23_laser_1 = tagsIntimatePrecision,
	ToG_Red_Dot_2 = tagsIntimatePrecision,
	ToG_Red_Dot_3 = tagsIntimatePrecision,
	G11_Barrel_def_1 = tagsIntimateStrategic,
	rpk_to762wp = tagsIntimateStrategic,
	Automag_Barrel_50bmg_def = tagsIntimateStrategic,
	BarrelNormalImproved = tagsIntimateStrategic,
	Auto5_Basic_LMag = tagsIntimateStrategic,
	Type56A_Barrel_def_1 = tagsIntimateStrategic,
	hk33_barrel_def_1 = tagsIntimateStrategic,
	STG44_Barrel_def_1 = tagsIntimateStrategic,
	Win97_Barrel_def_1 = tagsIntimateStrategic,
	FN2000_barrel_def_1 = tagsIntimateStrategic,
	Type56B_Barrel_def_1 = tagsIntimateStrategic,
	Spas12_Barrel_def_1 = tagsIntimateStrategic,
	FAMAE_barrel_def_1 = tagsIntimateStrategic,
	m76_barrel_def_1 = tagsIntimateStrategic,
	AN94_Barrel_def_1 = tagsIntimateStrategic,
	AR10_barrel_def = tagsIntimateStrategic,
	C96R_barrel_def_1 = tagsIntimateStrategic,
	Papovka_Barrel_def_1 = tagsIntimateStrategic,
	DeLisle_barrel_def_1 = tagsIntimateStrategic,
	RK62_Barrel_def_1 = tagsIntimateStrategic,
	Caws_Barrel_def_1 = tagsIntimateStrategic,
	G43_Barrel_def_1 = tagsIntimateStrategic,
	Tokarev_Barrel_def_1 = tagsIntimateStrategic,
	FNMD_barrel_def_1 = tagsIntimateStrategic,
	Mac11_Barrel_def_1 = tagsIntimateStrategic,
	U100_Barrel_def_1 = tagsIntimateStrategic,
	VSK94_barrel_def_1 = tagsIntimateStrategic,
	FP6_Barrel_def_1 = tagsIntimateStrategic,
	M48_barrel_def_1 = tagsIntimateStrategic,
	mk23_barrel_def_1 = tagsIntimateStrategic,
	VigM2_Barrel_def_1 = tagsIntimateStrategic,
	EM2_barrel_def_1 = tagsIntimateStrategic,
	BM59_barrel_def = tagsIntimateStrategic,
	M70D_barrel_def_1 = tagsIntimateStrategic,
	Type56D_Barrel_def_1 = tagsIntimateStrategic,
	CondorN_Barrel_def_1 = tagsIntimateStrategic,
	Type56C_Barrel_def_1 = tagsIntimateStrategic,
	SKS_Barrel_def_1 = tagsIntimateStrategic,
	VSS_Barrel_def_1 = tagsIntimateStrategic,
	BrenMK1_Barrel_def_1 = tagsIntimateStrategic,
	MP7_Barrel_def_1 = tagsIntimateStrategic,
	M1897_barrel_def = tagsIntimateStrategic,
	Condor_Barrel_def_1 = tagsIntimateStrategic,
	MAC2429_barrel_def_1 = tagsIntimateStrategic,
	M82_barrel_def_1 = tagsIntimateStrategic,
	RPD_barrel_def_1 = tagsIntimateStrategic,
	FG42_Barrel_def_1 = tagsIntimateStrategic,
	SSG69_Barrel_def_1 = tagsIntimateStrategic,
	BarrelNormal = tagsIntimateStrategic,
	M70_barrel_def_1 = tagsIntimateStrategic,
	MicroUZI_Barrel_def_1 = tagsIntimateStrategic,
	AR10_barrel_com = tagsIntimateStrategic,
	Mosin_Barrel_def_1 = tagsIntimateStrategic,
	G3_Barrel_def_1 = tagsIntimateStrategic,
	M60_Barrel_def_1 = tagsIntimateStrategic,
	PPSh_Barrel_def_1 = tagsIntimateStrategic,
	SteyrS_Barrel_def_1 = tagsIntimateStrategic,
	PP91_Barrel_def_1 = tagsIntimateStrategic,
	M1911_Barrel_def_1 = tagsIntimateStrategic,
	B93RR_barrel_def_1 = tagsIntimateStrategic,
	Auto5_Basic_NMag = tagsIntimateStrategic,
	NTW_20_barrel_def_1 = tagsIntimateStrategic,
	hk23e_barrel_def_1 = tagsIntimateStrategic,
	Viking_Barrel_def_1 = tagsIntimateStrategic,
	G3A3_barrel_def_1 = tagsIntimateStrategic,
	Papovka2_Barrel_def_1 = tagsIntimateStrategic,
	A91_762_barrel_def_1 = tagsIntimateStrategic,
	L85A1_barrel_def_1 = tagsIntimateStrategic,
	RK95_Barrel_def_1 = tagsIntimateStrategic,
	m625_barrel_def_1 = tagsIntimateStrategic,
	LeeEn_Barrel_def_1 = tagsIntimateStrategic,
	B93R_Barrel_def_1 = tagsIntimateStrategic,
	AWP_Barrel_def_1 = tagsIntimateStrategic,
	Stechkin_Barrel_def_1 = tagsIntimateStrategic,
	P08_Barrel_def_1 = tagsIntimateStrategic,
	Automag_Barrel_def_1 = tagsIntimateStrategic,
	RAT_TOG_CompensatorNoEntity = tagsIntimateStrategic,
	RAT_pap_compensator = tagsIntimateStrategic,
	FN2000_gasblock_ext_1 = tagsIntimateStrategic,
	FN2000_gasblock_def_1 = tagsIntimateStrategic,
	lever_action = tagsIntimateStrategic,
	Bolt_action_scout = tagsIntimateStrategic,
	Bolt_action = tagsIntimateStrategic,
	bullup = tagsIntimateStrategic,
	hk33_lower_modern_1 = tagsIntimateStrategic,
	_Master_ReceiverFullAuto_TOG = tagsIntimateStrategic,
	ToG_Revolver_freeswap = tagsIntimateStrategic,
	handgun_freeswap = tagsIntimateStrategic,
	MicroUZI_freeswap = tagsIntimateStrategic,
	m14_component_recoil = tagsIntimateStrategic,
	_Master_ReceiverBurst_TOG = tagsIntimateStrategic,
	hk33_lower_classic_1 = tagsIntimateStrategic,
	R_VSS_suppressor = tagsIntimateStrategic,
	Condor_Holder_magblock_1 = tagsIntimateStrategic,
	Condor_Holder_black_1 = tagsIntimateStrategic,
	Type56A_Bolt_1 = tagsIntimateStrategic,
	Condor_Holder_tan_1 = tagsIntimateStrategic,
	Papovka2_Bolt_1 = tagsIntimateStrategic,
	Type56D_Bolt_1 = tagsIntimateStrategic,
	Type56B_Bolt_1 = tagsIntimateStrategic,
	Papovka_Bolt_1 = tagsIntimateStrategic,
	Type56C_Bolt_1 = tagsIntimateStrategic,
	Condor_Holder_green_1 = tagsIntimateStrategic,
	FN2000_handguard_2 = tagsIntimateStrategic,
	AKSU_Hanguard_Basic = tagsIntimateStrategic,
	AK47_Handguard_basic = tagsIntimateStrategic,
	FN2000_handguard_3 = tagsIntimateStrategic,
	FNFAL_Handguard = tagsIntimateStrategic,
	hk33_handguard_cl_1 = tagsIntimateStrategic,
	RK62_Handguard_def_1 = tagsIntimateStrategic,
	RK95_Handguard_def_1 = tagsIntimateStrategic,
	RPK74_Hanguard_Basic = tagsIntimateStrategic,
	MuzzleBooster_Glock18 = tagsIntimateStrategic,
	hk33_handguard_new_1 = tagsIntimateStrategic,
	MagNormalFine = tagsIntimateStrategic,
	AR10_mag_fine = tagsIntimateStrategic,
	_Master_MagNormalFine = tagsIntimateStrategic,
	M60_Mag_bag_1 = tagsIntimateStrategic,
	mk23_mag_ext_1 = tagsIntimateStrategic,
	M1918A2_mag_ext_1 = tagsIntimateStrategic,
	Papovka_Mag_ext_c_1 = tagsIntimateStrategic,
	M82_mag_ext_1 = tagsIntimateStrategic,
	MagLarge_1 = tagsIntimateStrategic,
	MagLarge_3 = tagsIntimateStrategic,
	MagLarge_5 = tagsIntimateStrategic,
	NTW20_Magazine_ext_1 = tagsIntimateStrategic,
	A91_762_mag_ext_1 = tagsIntimateStrategic,
	MagLarge_4 = tagsIntimateStrategic,
	MagLarge_11 = tagsIntimateStrategic,
	Papovka2_Mag_ext_c_1 = tagsIntimateStrategic,
	U100_magazine_ext_1 = tagsIntimateStrategic,
	MagLarge_7 = tagsIntimateStrategic,
	MagLarge_10 = tagsIntimateStrategic,
	Tokarev_Mag_ext_1 = tagsIntimateStrategic,
	_Master_MagLarge = tagsIntimateStrategic,
	RK95_Mag_ext_1 = tagsIntimateStrategic,
	MagLarge = tagsIntimateStrategic,
	uspr_mag_ext_1 = tagsIntimateStrategic,
	MicroUZI_Mag_ext_1 = tagsIntimateStrategic,
	VSS_Mag_ext_1 = tagsIntimateStrategic,
	hk33_magazine_31 = tagsIntimateStrategic,
	PPSh_Mag_ext_1 = tagsIntimateStrategic,
	Papovka2_Mag_ext_1 = tagsIntimateStrategic,
	WA2000_Mag_L_1 = tagsIntimateStrategic,
	BrenMK1_Mag_ext_1 = tagsIntimateStrategic,
	AN94_Mag_ext_1 = tagsIntimateStrategic,
	SSG69_Mag_ext_1 = tagsIntimateStrategic,
	RK62_Mag_ext_1 = tagsIntimateStrategic,
	P08_Mag_ext_1 = tagsIntimateStrategic,
	B93RR_mag_ext_1 = tagsIntimateStrategic,
	G11_Mag_ext_1 = tagsIntimateStrategic,
	Automag_Mag_ext_1 = tagsIntimateStrategic,
	M1911_Mag_ext_1 = tagsIntimateStrategic,
	Viking_mag_ext_1 = tagsIntimateStrategic,
	FG42_Mag_ext_1 = tagsIntimateStrategic,
	AWP_mag_ext_1 = tagsIntimateStrategic,
	CAWS_Mag_L_1 = tagsIntimateStrategic,
	MP7_Mag_ext_1 = tagsIntimateStrategic,
	Papovka_Mag_ext_1 = tagsIntimateStrategic,
	G43_Mag_ext_1 = tagsIntimateStrategic,
	TAR21_Mag_ext_1 = tagsIntimateStrategic,
	G3_Mag_ext_1 = tagsIntimateStrategic,
	PP91_Mag_ext_1 = tagsIntimateStrategic,
	ToG_Comp_Pstl_expmag_1 = tagsIntimateStrategic,
	MagLarge_12 = tagsIntimateStrategic,
	MagLarge_8 = tagsIntimateStrategic,
	MagLarge_6 = tagsIntimateStrategic,
	MagLarge_9 = tagsIntimateStrategic,
	MagLarge_2 = tagsIntimateStrategic,
	MagLargeFine_7 = tagsIntimateStrategic,
	MagLargeFine_4 = tagsIntimateStrategic,
	MagLargeFine_11 = tagsIntimateStrategic,
	MagLargeFine_10 = tagsIntimateStrategic,
	Glock17_Mag_ext_1 = tagsIntimateStrategic,
	MagLargeFine_3 = tagsIntimateStrategic,
	MagLargeFine_1 = tagsIntimateStrategic,
	MagLargeFine_5 = tagsIntimateStrategic,
	MagLargeFine = tagsIntimateStrategic,
	_Master_MagLargeFine = tagsIntimateStrategic,
	_Master_DrumMag = tagsIntimateStrategic,
	hk33_drum_mag_1 = tagsIntimateStrategic,
	MagLargeFine_8 = tagsIntimateStrategic,
	MagLargeFine_12 = tagsIntimateStrategic,
	MagLargeFine_2 = tagsIntimateStrategic,
	MagLargeFine_6 = tagsIntimateStrategic,
	MagLargeFine_9 = tagsIntimateStrategic,
	G11_Mag_ext2_1 = tagsIntimateStrategic,
	MP7_Mag_quick_1 = tagsIntimateStrategic,
	FAMAE_mag3_1 = tagsIntimateStrategic,
	AR10_mag_dual = tagsIntimateStrategic,
	MagQuick = tagsIntimateStrategic,
	FAMAE_mag2_1 = tagsIntimateStrategic,
	ToG_Comp_Pstl_ergmag_1 = tagsIntimateStrategic,
	MP7_Mag_extQ_1 = tagsIntimateStrategic,
	R_MagQuickLarge = tagsIntimateStrategic,
	Viking_mag_extQ_1 = tagsIntimateStrategic,
	hk33_magazine_11 = tagsIntimateStrategic,
	m76_mag_def_1 = tagsIntimateStrategic,
	AN94_Mag_def_1 = tagsIntimateStrategic,
	RK62_Mag_def_3 = tagsIntimateStrategic,
	Type56B_Mag_def_1 = tagsIntimateStrategic,
	Sten_mag_def_1 = tagsIntimateStrategic,
	FG42_Mag_def_1 = tagsIntimateStrategic,
	TAR21_Mag_def_1 = tagsIntimateStrategic,
	RK62_Mag_def_1 = tagsIntimateStrategic,
	mk23_mag_def_1 = tagsIntimateStrategic,
	M60_Mag_def_1 = tagsIntimateStrategic,
	Type56C_Mag_def_1 = tagsIntimateStrategic,
	MAC2429_Mag_def_1 = tagsIntimateStrategic,
	ToG_Comp_Pstl_defmag_1 = tagsIntimateStrategic,
	Type56D_Mag_def_1 = tagsIntimateStrategic,
	Papovka2_Mag_def_1 = tagsIntimateStrategic,
	FAMAE_mag1_1 = tagsIntimateStrategic,
	Mac11_Mag_def_1 = tagsIntimateStrategic,
	G3A3_magazine_1 = tagsIntimateStrategic,
	M70_mag_def_1 = tagsIntimateStrategic,
	RK95_Mag_def_1 = tagsIntimateStrategic,
	Type56A_Mag_def_1 = tagsIntimateStrategic,
	STG44_Mag_def_1 = tagsIntimateStrategic,
	WA2000_Mag_Def_1 = tagsIntimateStrategic,
	M1918A2_mag_def_1 = tagsIntimateStrategic,
	M82_mag_def_1 = tagsIntimateStrategic,
	AR10_mag_def = tagsIntimateStrategic,
	EM2_mag_def_1 = tagsIntimateStrategic,
	P08_Mag_def_1 = tagsIntimateStrategic,
	U100_magazine_def_1 = tagsIntimateStrategic,
	G11_Mag_def_1 = tagsIntimateStrategic,
	MagNormal = tagsIntimateStrategic,
	FN2000_mag_def_1 = tagsIntimateStrategic,
	BM59_mag_def = tagsIntimateStrategic,
	MP7_Mag_def_1 = tagsIntimateStrategic,
	VigM2_mag_def_1 = tagsIntimateStrategic,
	_Master_MagNormal = tagsIntimateStrategic,
	AWP_mag_def_1 = tagsIntimateStrategic,
	FNMD_mag_def_1 = tagsIntimateStrategic,
	G3_Mag_def_1 = tagsIntimateStrategic,
	uspr_mag_def_1 = tagsIntimateStrategic,
	RPD_mag_def_1 = tagsIntimateStrategic,
	BrenMK1_Mag_def_1 = tagsIntimateStrategic,
	ToG_Comp_Pstl_finemag_1 = tagsIntimateStrategic,
	LeeEn_Mag_def_1 = tagsIntimateStrategic,
	NTW20_Magazine_def_1 = tagsIntimateStrategic,
	Papovka_Mag_def_1 = tagsIntimateStrategic,
	Glock17_mag_def_1 = tagsIntimateStrategic,
	DeLisle_mag_def_1 = tagsIntimateStrategic,
	A91_762_mag_def_1 = tagsIntimateStrategic,
	Automag_Mag_def_1 = tagsIntimateStrategic,
	Tokarev_Mag_def_1 = tagsIntimateStrategic,
	VSS_Mag_def_1 = tagsIntimateStrategic,
	VSK94_Mag_def_1 = tagsIntimateStrategic,
	M70D_mag_def_1 = tagsIntimateStrategic,
	CAWS_Mag_Def_1 = tagsIntimateStrategic,
	SSG69_Mag_def_1 = tagsIntimateStrategic,
	G43_Mag_def_1 = tagsIntimateStrategic,
	hk23e_mag_1 = tagsIntimateStrategic,
	M1911_Mag_def_1 = tagsIntimateStrategic,
	Viking_mag_def_1 = tagsIntimateStrategic,
	PP91_Mag_def_1 = tagsIntimateStrategic,
	PPSh_Mag_def_1 = tagsIntimateStrategic,
	MicroUZI_Mag_def_1 = tagsIntimateStrategic,
	B93RR_mag_def_1 = tagsIntimateStrategic,
	L85A1_mag_def_1 = tagsIntimateStrategic,
	ToG_Scope_Block = tagsIntimateStrategic,
	M24_Mount_Front = tagsIntimateStrategic,
	AUGMount = tagsIntimateStrategic,
	M24_Mount = tagsIntimateStrategic,
	hk23e_handle_fld_1 = tagsIntimateStrategic,
	FN2000_mountfront_1 = tagsIntimateStrategic,
	hk23e_handle_unfld_1 = tagsIntimateStrategic,
	AR10_sideblock = tagsIntimateStrategic,
	MP7_siderails_1 = tagsIntimateStrategic,
	AR10_siderails = tagsIntimateStrategic,
	hk23e_siderail_1 = tagsIntimateStrategic,
	AWP_Muzzle_1 = tagsIntimateStrategic,
	FN2000_Muzzle_1 = tagsIntimateStrategic,
	L85A1_muzzle_def_1 = tagsIntimateStrategic,
	RK95_Muzzle_def_1 = tagsIntimateStrategic,
	TAR21_Muzzle_def_1 = tagsIntimateStrategic,
	RAT_TOG_compensator = tagsIntimateStrategic,
	AUGCompensator_01 = tagsIntimateStrategic,
	hk23e_muzzle_1 = tagsIntimateStrategic,
	RK62_Muzzle_def_1 = tagsIntimateStrategic,
	hk33_muzzle_1 = tagsIntimateStrategic,
	G3A3_muzzle_1 = tagsIntimateStrategic,
	Compensator = tagsIntimateStrategic,
	ToG_Shotgun_Silencer = tagsIntimateStrategic,
	FN2000_silencer_1 = tagsIntimateStrategic,
	M60_Muzzle_def_1 = tagsIntimateStrategic,
	M134_Muzzlebooster = tagsIntimateStrategic,
	MuzzleBooster = tagsIntimateStrategic,
	Galil_Brake_Default = tagsIntimateStrategic,
	Compensator_Glock = tagsIntimateStrategic,
	AUGCompensator_03 = tagsIntimateStrategic,
	ImprovisedSuppressor_Anaconda = tagsIntimateStrategic,
	Suppressor_Anaconda = tagsIntimateStrategic,
	Suppressor = tagsIntimateStrategic,
	SteyrS_Muzzle_def_1 = tagsIntimateStrategic,
	MP7_Supr_1 = tagsIntimateStrategic,
	RAT_TOG_suppressor_762 = tagsIntimateStrategic,
	RAT_VSK_Suppressor = tagsIntimateStrategic,
	RAT_TOG_suppressor_wp = tagsIntimateStrategic,
	RAT_TOG_suppressor = tagsIntimateStrategic,
	ImprovisedSuppressor = tagsIntimateStrategic,
	M1918A2_muzzle_def_1 = tagsIntimateStrategic,
	M14_Default_Muzzle = tagsIntimateStrategic,
	G3_Muzzle_def_1 = tagsIntimateStrategic,
	ToG_VFX_Muzzle = tagsIntimateStrategic,
	component_22mm_grenade = tagsIntimateStrategic,
	Placeholder_Muzzle = tagsIntimateStrategic,
	LionRoar_compensator = tagsIntimateStrategic,
	U100_muzzle_1 = tagsIntimateStrategic,
	AR10_muzzle_def = tagsIntimateStrategic,
	DefaultMuzzle_HK21 = tagsIntimateStrategic,
	Compensator_cosmetic = tagsIntimateStrategic,
	CAWS_Muzzle_def_1 = tagsIntimateStrategic,
	G11_Rail_15 = tagsIntimateStrategic,
	G11_Rail_6 = tagsIntimateStrategic,
	L85A1_scope_1 = tagsIntimateStrategic,
	G11_Rail_12 = tagsIntimateStrategic,
	G11_Rail_11 = tagsIntimateStrategic,
	G11_Rail_10 = tagsIntimateStrategic,
	G11_Rail_13 = tagsIntimateStrategic,
	G11_Rail_14 = tagsIntimateStrategic,
	FN2000_ironsight_1 = tagsIntimateStrategic,
	FP6_Ironsight_1 = tagsIntimateStrategic,
	ToG_Railmount_placeh = tagsIntimateStrategic,
	hk23e_rail_top_1 = tagsIntimateStrategic,
	hk33_top_rail_1 = tagsIntimateStrategic,
	EM2_rail_1 = tagsIntimateStrategic,
	AWP_rail_1 = tagsIntimateStrategic,
	G11_Rail_1 = tagsIntimateStrategic,
	ToG_Rail_1 = tagsIntimateStrategic,
	FN2000_Toprail_1 = tagsIntimateStrategic,
	Picatinny_Rail_1 = tagsIntimateStrategic,
	L85A1_toprail_1 = tagsIntimateStrategic,
	UVDot = tagsIntimateStrategic,
	UVDot_PSG_M1 = tagsIntimateStrategic,
	UVDot_aa12 = tagsIntimateStrategic,
	ToG_UV_Dot_1 = tagsIntimateStrategic,
	ToG_UV_Dot_2 = tagsIntimateStrategic,
	side_2_empty = tagsIntimateStrategic,
	ToG_UV_Dot_3 = tagsIntimateStrategic,
	StockBump = tagsIntimateStrategic,
	HIll_StockGalil_01 = tagsIntimateStrategic,
	RK95_Stock_def_1 = tagsIntimateStrategic,
	StockNormal_AR_BurstOnly = tagsIntimateStrategic,
	_Master_StockNormalUnfolded_TOG = tagsIntimateStrategic,
	AN94_Stock_def_1 = tagsIntimateStrategic,
	foldable_StockNormal = tagsIntimateStrategic,
	AR10_stock_def = tagsIntimateStrategic,
	BM59MK1_stock = tagsIntimateStrategic,
	BrenMK1_Stock_def_1 = tagsIntimateStrategic,
	Condor_Stock_def_1 = tagsIntimateStrategic,
	CondorN_Stock_def_1 = tagsIntimateStrategic,
	DeLisle_stock_def_1 = tagsIntimateStrategic,
	EM2_stock_def_1 = tagsIntimateStrategic,
	FG42_Stock_def_1 = tagsIntimateStrategic,
	FNMD_stock_def_1 = tagsIntimateStrategic,
	FP6_Stock_def_1 = tagsIntimateStrategic,
	G3_Stock_def_1 = tagsIntimateStrategic,
	G3A3_Stock_1 = tagsIntimateStrategic,
	hk23e_stock_def_1 = tagsIntimateStrategic,
	hk33_Stock_1 = tagsIntimateStrategic,
	LeeEn_Stock_def_1 = tagsIntimateStrategic,
	M60_Stock_def_1 = tagsIntimateStrategic,
	m76_stock_def_1 = tagsIntimateStrategic,
	MAC2429_Stock_def_1 = tagsIntimateStrategic,
	Papovka_Stock_def_1 = tagsIntimateStrategic,
	Papovka_Stock_def_cross1_1 = tagsIntimateStrategic,
	Papovka_Stock_def_type56_1 = tagsIntimateStrategic,
	Papovka2_Stock_def_1 = tagsIntimateStrategic,
	Papovka2_Stock_def_cross1_1 = tagsIntimateStrategic,
	PPSh_Stock_def_1 = tagsIntimateStrategic,
	RK62_Stock_def_1 = tagsIntimateStrategic,
	RPD_stock_def_1 = tagsIntimateStrategic,
	STG44_Stock_def_1 = tagsIntimateStrategic,
	StockNormal = tagsIntimateStrategic,
	Type56A_stock_def_1 = tagsIntimateStrategic,
	Type56A_stock_def_c = tagsIntimateStrategic,
	Type56B_stock_def_1 = tagsIntimateStrategic,
	Type56B_stock_def_c = tagsIntimateStrategic,
	Type56C_stock_def_1 = tagsIntimateStrategic,
	Type56C_stock_def_c = tagsIntimateStrategic,
	Type56D_stock_def_1 = tagsIntimateStrategic,
	Type56D_stock_def_c = tagsIntimateStrategic,
	U100_Stock_def_1 = tagsIntimateStrategic,
	VSS_Stock_def_1 = tagsIntimateStrategic,
	ThunderTech_Hurricane_1 = tagsIntimateStrategic,
	ThunderTech_Tornado_1 = tagsIntimateStrategic,
	ThunderTech_Typhoon_1 = tagsIntimateStrategic,
	ThunderTech_Storm_1 = tagsIntimateStrategic,
	Sovitron_Kmrad_1 = tagsIntimateStrategic,
	ThunderTech_Bolt_1 = tagsIntimateStrategic,
	ThunderTech_Whirlwind_1 = tagsIntimateStrategic,
	ThunderTech_Basic_1 = tagsIntimateStrategic,
	ThunderTech_Monsoon_1 = tagsIntimateStrategic,
	ThunderTech_Cyclone_1 = tagsIntimateStrategic,
	ThunderTech_Titan_1 = tagsIntimateStrategic,
	ThunderTech_Hyperion_1 = tagsIntimateStrategic,
	ThunderTech_Hyperion = tagsIntimateStrategic,
	ThunderTech_Whirlwind = tagsIntimateStrategic,
	ThunderTech_Typhoon = tagsIntimateStrategic,
	Sovitron_Kmrad = tagsIntimateStrategic,
	ThunderTech_Basic = tagsIntimateStrategic,
	ThunderTech_Tornado = tagsIntimateStrategic,
	ThunderTech_Hurricane = tagsIntimateStrategic,
	ThunderTech_Titan = tagsIntimateStrategic,
	ThunderTech_Monsoon = tagsIntimateStrategic,
	ThunderTech_Bolt = tagsIntimateStrategic,
	ThunderTech_Storm = tagsIntimateStrategic,
	ThunderTech_Cyclone = tagsIntimateStrategic,
	NoiseX_Muffler = tagsIntimateStrategic,
	Silentium_Mute = tagsIntimateStrategic,
	NoiseX_Symphony = tagsIntimateStrategic,
	Silentium_Shadow = tagsIntimateStrategic,
	Silentium_Phantom = tagsIntimateStrategic,
	Silentium_Ghost = tagsIntimateStrategic,
	NoiseX_SoundGuard = tagsIntimateStrategic,
	Silentium_Ninja = tagsIntimateStrategic,
	Silentium_Whisper = tagsIntimateStrategic,
	NoiseX_Mirage = tagsIntimateStrategic,
	NoiseX_Sonic = tagsIntimateStrategic,
	Silentium_Nighthawk = tagsIntimateStrategic,
	Silentium_Nighthawk_1 = tagsIntimateStrategic,
	NoiseX_SymphonyPro = tagsIntimateStrategic,
	Silentium_Ninja_1 = tagsIntimateStrategic,
	Silentium_Shadow_1 = tagsIntimateStrategic,
	Silentium_Whisper_1 = tagsIntimateStrategic,
	Silentium_Ghost_1 = tagsIntimateStrategic,
	NoiseX_SoundGuardPro = tagsIntimateStrategic,
	NoiseX_SonicPro = tagsIntimateStrategic,
	NoiseX_MiragePro = tagsIntimateStrategic,
	NoiseX_MufflerPro = tagsIntimateStrategic,
	Silentium_Phantom_1 = tagsIntimateStrategic,
	Silentium_Mute_1 = tagsIntimateStrategic,
	single_action = tagsIntimateStrategic,
	single_action_tex = tagsIntimateStrategic,
	SADA_action = tagsIntimateStrategic,
	double_action = tagsIntimateStrategic,
	TacGrip_M14 = tagsIntimateStrategic,
	TacGrip = tagsIntimateStrategic,
	VerticalGrip_Commando = tagsIntimateStrategic,
	VerticalGrip_aug = tagsIntimateStrategic,
	VerticalGrip_M14 = tagsIntimateStrategic,
	VerticalGrip_M16 = tagsIntimateStrategic,
	M60_Grip_und_1 = tagsIntimateStrategic,
	G11_Grip_CAWS_1 = tagsIntimateStrategic,
	Caws_Grip_def_1 = tagsIntimateStrategic,
	M60_Grip_side_1 = tagsIntimateStrategic,
	VerticalGrip = tagsIntimateStrategic,
	B93R_Under_unfld_1 = tagsIntimateStrategic,
	MP7_Grip_unfld_1 = tagsIntimateStrategic,
	FN2000_Frontrail_1 = tagsIntimateStrategic,
	hk33_side_block_1 = tagsIntimateStrategic,
	M16_Handguard = tagsIntimateStrategic,
	hk23e_sidegrip_1 = tagsIntimateStrategic,
	Galil_Handguard_Default = tagsIntimateStrategic,
	Handguard_Commando = tagsIntimateStrategic,
	MP5_Handguard = tagsIntimateStrategic,
	hk33_side_rails_1 = tagsIntimateStrategic,
	BarrelLong_AUG = tagsPrecisionStrategic,
	BarrelLongImproved_AUG = tagsPrecisionStrategic,
	long_barrel_AUG_light = tagsPrecisionStrategic,
	AK47_Bipod = tagsPrecisionStrategic,
	G11_Bipod_1 = tagsPrecisionStrategic,
	Bipod_MG42 = tagsPrecisionStrategic,
	M60_Bip_unfld_1 = tagsPrecisionStrategic,
	RPD_bipod_unfld_1 = tagsPrecisionStrategic,
	AN94_Bip_def_1 = tagsPrecisionStrategic,
	FG42_Bipod_1 = tagsPrecisionStrategic,
	ToG_Bipod_1 = tagsPrecisionStrategic,
	hk33_bipod_unfld_1 = tagsPrecisionStrategic,
	Bipod = tagsPrecisionStrategic,
	BrenMK1_Bipod_unfld_1 = tagsPrecisionStrategic,
	hk23e_bipod_unfld_1 = tagsPrecisionStrategic,
	Bipod_m82 = tagsPrecisionStrategic,
	PKM_Bipod_Unfold_1 = tagsPrecisionStrategic,
	AR10_bipod_unfld = tagsPrecisionStrategic,
	U100_bipod_unfld_1 = tagsPrecisionStrategic,
	FNMD_bipod_unfld_1 = tagsPrecisionStrategic,
	NTW20_bipod_unfld_1 = tagsPrecisionStrategic,
	MAC2429_Bipod_unfld_1 = tagsPrecisionStrategic,
	BM59_bipod_unfld = tagsPrecisionStrategic,
	WA2000_Bipod_Unfold_1 = tagsPrecisionStrategic,
	Papovka2_Bay_unfld_1 = tagsPrecisionStrategic,
	Type56C_Bay_unfld_1 = tagsPrecisionStrategic,
	SKS_Bay_unfld_1 = tagsPrecisionStrategic,
	Papovka_Bay_unfld_1 = tagsPrecisionStrategic,
	_Master_BayonetUnfolded_TOG = tagsPrecisionStrategic,
	Type56D_Bay_unfld_1 = tagsPrecisionStrategic,
	Type56A_Bay_unfld_1 = tagsPrecisionStrategic,
	Type56B_Bay_unfld_1 = tagsPrecisionStrategic,
	browning_bipod = tagsPrecisionStrategic,
	SKS_Scope = tagsPrecisionStrategic,
	_Master_SSG69_Scope_TOG = tagsPrecisionStrategic,
	SSG69_Scope_1 = tagsPrecisionStrategic,
	LROpticsAdvanced = tagsPrecisionStrategic,
	RAT_TOG_LRoptics_advanced = tagsPrecisionStrategic,
	RAT_TOG_LRoptics_advanced_rpk_mount = tagsPrecisionStrategic,
	PSG_DefaultScope = tagsPrecisionStrategic,
	RAT_TOG_PSGScope = tagsPrecisionStrategic,
	RAT_TOG_PSGScope_rpk_mount = tagsPrecisionStrategic,
	WA2000_Scope_1 = tagsPrecisionStrategic,
	AWP_Scope_1 = tagsPrecisionStrategic,
	NTW_20_Scope_1 = tagsPrecisionStrategic,
	AWP_Stock_rst_1 = tagsPrecisionStrategic,
	Bipod_Galil = tagsPrecisionStrategic,
	Bipod_Under = tagsPrecisionStrategic,
	G11_Rail_9 = tagsTacticalPrecision,
	FN2000_Scope_1 = tagsTacticalPrecision,
	G11_Rail_7 = tagsTacticalPrecision,
	-- "_Master_PSO-1M2_Scope_TOG" = tagsTacticalPrecision,
	VSS_Scope_1 = tagsTacticalPrecision,
	SteyrS_Scope_1 = tagsTacticalPrecision,
	_Master_SteyrS_Scope_TOG = tagsTacticalPrecision,
	G11_Scope_1 = tagsTacticalPrecision,
	LROptics_DragunovDefault = tagsTacticalPrecision,
	RAT_TOG_LRoptics_rpk_mount = tagsTacticalPrecision,
	RAT_TOG_LRoptics = tagsTacticalPrecision,
	LROptics = tagsTacticalPrecision,
	_Master_m76_scope_TOG = tagsTacticalPrecision,
	m76_scope_1 = tagsTacticalPrecision,
	AN94_Scope_1 = tagsTacticalPrecision,
	RAT_TOG_thermal = tagsTacticalPrecision,
	RAT_TOG_thermal_rpk_mount = tagsTacticalPrecision,
	ThermalScope = tagsTacticalPrecision,
	ThermalScope_2 = tagsTacticalPrecision,
	ThermalScope_1 = tagsTacticalPrecision,
	Auto5_Long_LMag = tagsTacticalStrategic,
	Condor_Barrel_ext_1 = tagsTacticalStrategic,
	Auto5_Long_NMag = tagsTacticalStrategic,
	M1897_barrel_ext = tagsTacticalStrategic,
	CondorN_Barrel_ext_1 = tagsTacticalStrategic,
	BarrelHeavy = tagsTacticalStrategic,
	Barrel50BMG_DesertEagle = tagsTacticalStrategic,
	winni_to54r = tagsTacticalStrategic,
	BarrelLongShotgun = tagsTacticalStrategic,
	Spas12_Barrel_ext_1 = tagsTacticalStrategic,
	M82_barrel_ext_1 = tagsTacticalStrategic,
	U100_Barrel_ext_1 = tagsTacticalStrategic,
	FAMAE_barrel_ext_1 = tagsTacticalStrategic,
	MAC2429_barrel_ext_1 = tagsTacticalStrategic,
	FN2000_barrel_ext_1 = tagsTacticalStrategic,
	AR10_barrel_ext = tagsTacticalStrategic,
	A91_762_barrel_ext_1 = tagsTacticalStrategic,
	L85A1_barrel_ext_1 = tagsTacticalStrategic,
	M48_barrel_ext_1 = tagsTacticalStrategic,
	C96R_barrel_ext_1 = tagsTacticalStrategic,
	FNMD_barrel_ext_1 = tagsTacticalStrategic,
	BM59_barrel_ext = tagsTacticalStrategic,
	mk23_barrel_ext_1 = tagsTacticalStrategic,
	EM2_barrel_ext_1 = tagsTacticalStrategic,
	ToG_Comp_AR_Barrel_Long_2 = tagsTacticalStrategic,
	B93RR_barrel_ext_1 = tagsTacticalStrategic,
	B93R_Barrel_ext_1 = tagsTacticalStrategic,
	MicroUZI_Barrel_ext_1 = tagsTacticalStrategic,
	M1911_Barrel_ext_1 = tagsTacticalStrategic,
	Viking_Barrel_ext_1 = tagsTacticalStrategic,
	Mac11_Barrel_ext_1 = tagsTacticalStrategic,
	Automag_Barrel_ext_1 = tagsTacticalStrategic,
	BarrelLong_handgun = tagsTacticalStrategic,
	PP91_Barrel_ext_1 = tagsTacticalStrategic,
	P08_Barrel_Long_1 = tagsTacticalStrategic,
	ToG_Comp_Pstl_Barrel_Long = tagsTacticalStrategic,
	VigM2_Barrel_ext_1 = tagsTacticalStrategic,
	ToG_Comp_AR_Barrel_Long_1_SMG = tagsTacticalStrategic,
	ToG_Comp_Pstl_Barrel_Long_1 = tagsTacticalStrategic,
	ToG_Comp_AR_Barrel_Long_2_SMG = tagsTacticalStrategic,
	M60_Barrel_ext_1 = tagsTacticalStrategic,
	STG44_Barrel_ext_1 = tagsTacticalStrategic,
	BarrelLong_jaggerMeister = tagsTacticalStrategic,
	BarrelLong = tagsTacticalStrategic,
	SteyrS_Barrel_ext_1 = tagsTacticalStrategic,
	VSS_Barrel_ext_1 = tagsTacticalStrategic,
	Type56A_Barrel_ext_1 = tagsTacticalStrategic,
	m76_barrel_ext_1 = tagsTacticalStrategic,
	BrenMK1_Barrel_ext_1 = tagsTacticalStrategic,
	FP6_Barrel_ext_1 = tagsTacticalStrategic,
	G11_Barrel_ext_1 = tagsTacticalStrategic,
	G43_Barrel_ext_1 = tagsTacticalStrategic,
	Type56C_Barrel_ext_1 = tagsTacticalStrategic,
	Mosin_Barrel_long_1 = tagsTacticalStrategic,
	M70D_barrel_ext_1 = tagsTacticalStrategic,
	Stechkin_Barrel_ext_1 = tagsTacticalStrategic,
	Papovka_Barrel_ext_1 = tagsTacticalStrategic,
	hk23e_barrel_ext_1 = tagsTacticalStrategic,
	Papovka2_Barrel_ext_1 = tagsTacticalStrategic,
	RK62_Barrel_ext_1 = tagsTacticalStrategic,
	PPSh_Barrel_ext_1 = tagsTacticalStrategic,
	G3_Barrel_ext_1 = tagsTacticalStrategic,
	m625_barrel_ext_1 = tagsTacticalStrategic,
	G3A3_barrel_ext_1 = tagsTacticalStrategic,
	Type56D_Barrel_ext_1 = tagsTacticalStrategic,
	RK95_Barrel_ext_1 = tagsTacticalStrategic,
	M70_barrel_ext_1 = tagsTacticalStrategic,
	hk33_barrel_ext_1 = tagsTacticalStrategic,
	AN94_Barrel_ext_1 = tagsTacticalStrategic,
	SSG69_Barrel_ext_1 = tagsTacticalStrategic,
	Tokarev_Barrel_ext_1 = tagsTacticalStrategic,
	LeeEn_Barrel_ext_1 = tagsTacticalStrategic,
	MP7_Barrel_ext_1 = tagsTacticalStrategic,
	Type56B_Barrel_ext_1 = tagsTacticalStrategic,
	SKS_Barrel_ext_1 = tagsTacticalStrategic,
	ToG_Comp_AR_Barrel_Long_1 = tagsTacticalStrategic,
	AWP_Barrel_ext_1 = tagsTacticalStrategic,
	FG42_Barrel_long_1 = tagsTacticalStrategic,
	RAT_TOG_SteyrS_Barrel_ext_556 = tagsTacticalStrategic,
	Caws_Barrel_long_1 = tagsTacticalStrategic,
	Automag_Barrel_50bmg_ext = tagsTacticalStrategic,
	BarrelLongImproved = tagsTacticalStrategic,
	BarrelLongImproved_handgun = tagsTacticalStrategic,
	BarrelHeavyLong = tagsTacticalStrategic,
	long_barrel_light_handgun = tagsTacticalStrategic,
	long_barrel_light = tagsTacticalStrategic,
	_Master_BayonetFolded_TOG = tagsTacticalStrategic,
	Type56A_Bay_fld_1 = tagsTacticalStrategic,
	SKS_Bay_fld_1 = tagsTacticalStrategic,
	Type56D_Bay_fld_1 = tagsTacticalStrategic,
	Type56B_Bay_fld_1 = tagsTacticalStrategic,
	Papovka_Bay_fld_1 = tagsTacticalStrategic,
	Papovka2_Bay_fld_1 = tagsTacticalStrategic,
	AK47_Launcher = tagsTacticalStrategic,
	M60_GrenadeLauncher_1 = tagsTacticalStrategic,
	GrenadeLauncher_AUG = tagsTacticalStrategic,
	FN2000_grndl_1 = tagsTacticalStrategic,
	Condor_Mag_XX_1 = tagsTacticalStrategic,
	Papovka_Grnd_unfld_1 = tagsTacticalStrategic,
	_Master_GrenadeLauncherUnfolded_TOG = tagsTacticalStrategic,
	Papovka2_Grnd_unfld_1 = tagsTacticalStrategic,
	M70D_grndl_unfld_1 = tagsTacticalStrategic,
	M70_grndl_unfld_1 = tagsTacticalStrategic,
	BM59_grndl_unfld = tagsTacticalStrategic,
	Papovka_Grnd_fld_1 = tagsTacticalStrategic,
	M70D_grndl_fld_1 = tagsTacticalStrategic,
	M70_grndl_fld_1 = tagsTacticalStrategic,
	Papovka2_Grnd_fld_1 = tagsTacticalStrategic,
	BM59_grndl_fld = tagsTacticalStrategic,
	_Master_GrenadeLauncherFolded_TOG = tagsTacticalStrategic,
	ToG_NatoGL = tagsTacticalStrategic,
	FullChoke = tagsTacticalStrategic,
	NTW20_stock_unfld_1 = tagsTacticalStrategic,
	AR10_stock_hvy = tagsTacticalStrategic,
	Automag_Stock_1 = tagsTacticalStrategic,
	BM59MK2_stock = tagsTacticalStrategic,
	C96R_Stock_1 = tagsTacticalStrategic,
	EM2_stock_hvy_1 = tagsTacticalStrategic,
	MAC2429_Stock_hvy_1 = tagsTacticalStrategic,
	Type56A_stock_hvy_c = tagsTacticalStrategic,
	Type56B_stock_hvy_c = tagsTacticalStrategic,
	Type56C_stock_hvy_c = tagsTacticalStrategic,
	Type56D_stock_hvy_c = tagsTacticalStrategic,
	U100_Stock_hvy_1 = tagsTacticalStrategic,
	StockHeavy_AR_BurstOnly = tagsTacticalStrategic,
	BrenMK1_Stock_hvy_1 = tagsTacticalStrategic,
	G3A3_stock_hvy_1 = tagsTacticalStrategic,
	hk23e_stock_hvy_1 = tagsTacticalStrategic,
	hk53_Stock_heavy = tagsTacticalStrategic,
	LeeEn_Stock_Heavy_1 = tagsTacticalStrategic,
	M60_Stock_hvy_1 = tagsTacticalStrategic,
	m76_stock_hvy_1 = tagsTacticalStrategic,
	Papovka_Stock_hvy_1 = tagsTacticalStrategic,
	Papovka_Stock_hvy_cross1_1 = tagsTacticalStrategic,
	Papovka2_Stock_hvy_1 = tagsTacticalStrategic,
	Papovka2_Stock_hvy_cross1_1 = tagsTacticalStrategic,
	PPSh_Stock_heavy_1 = tagsTacticalStrategic,
	RK62_Stock_hvy_1 = tagsTacticalStrategic,
	STG44_Stock_hvy_1 = tagsTacticalStrategic,
	StockHeavy = tagsTacticalStrategic,
	Type56A_stock_hvy_1 = tagsTacticalStrategic,
	Type56B_stock_hvy_1 = tagsTacticalStrategic,
	Type56C_stock_hvy_1 = tagsTacticalStrategic,
	Type56D_stock_hvy_1 = tagsTacticalStrategic,
	stock_uzi = tagsTacticalStrategic,
	VSK94_Stock_hvy_1 = tagsTacticalStrategic,
	GrenadeLauncher_Galil = tagsTacticalStrategic,
	GrenadeLauncher_M16A1 = tagsTacticalStrategic,
	G11_Grenadelauncher_1 = tagsTacticalStrategic,
	GrenadeLauncher = tagsTacticalStrategic,
	GrenadeLauncher_Commando = tagsTacticalStrategic,
	GrenadeLauncher_M14 = tagsTacticalStrategic,
}

Cuae_ExcludeComponents = {
	-- ToG shotguns range
	BarrelLongShotgun = true,
	M1897_barrel_ext = true,
	Auto5_Long_LMag = true,
	Auto5_Long_NMag = true,
	Caws_Barrel_long_1 = true,
	FP6_Barrel_ext_1 = true,
	Spas12_Barrel_ext_1 = true,
	CondorN_Barrel_ext_1 = true,
	Condor_Barrel_ext_1 = true,
	hk33_lower_classic_1 = true,
}

function Cuae_ExcludeComponents_DisallowSilencers()
	Cuae_ExcludeComponents.ImprovisedSuppressor = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.ImprovisedSuppressor_Anaconda = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.Suppressor = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.Suppressor_Anaconda = Cuae_LoadedModOptions.DisallowSilencers
	-- ToG
	Cuae_ExcludeComponents.FN2000_silencer_1 = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.ToG_Shotgun_Silencer = Cuae_LoadedModOptions.DisallowSilencers
	-- MoW
	Cuae_ExcludeComponents.MoW_Muz_Obs9 = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.MoW_Muz_Obs9s = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.MoW_Muz_Rev9 = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.MoW_Muz_Rev45 = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.MoW_Muz_Omega9 = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.MoW_Muz_N4 = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.MoW_Muz_Spectre = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.MoW_Muz_RotexIII = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.MoW_Muz_SR25 = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.MoW_Muz_MP9 = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.MoW_Muz_Vector = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.MoW_Muz_Phantom = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.MoW_Muz_TGPA = Cuae_LoadedModOptions.DisallowSilencers
	Cuae_ExcludeComponents.MoW_Muz_PBS1 = Cuae_LoadedModOptions.DisallowSilencers
	-- rato
	Cuae_ExcludeComponents.RAT_TOG_suppressor = Cuae_LoadedModOptions.DisallowSilencers
end

Cuae_ExcludeComponents_DisallowSilencers()

-- Build on OnMsg.ModsReloaded
Cuae_AllArmaments = {
	-- weapons
	Handgun = {},
	SMG = {},
	AssaultRifle = {},
	Sniper = {},
	Shotgun = {},
	MachineGun = {},
	FlareGun = {},
	MeleeWeapon = {},
	GrenadeLauncher = {},
	Mortar = {},
	MissileLauncher = {},
	-- utility
	Flare = {},
	Explosive = {},
	Flash = {},
	Fire = {},
	Smoke = {},
	Tear = {},
	Toxic = {},
	Timed = {},
	Proximity = {},
	Remote = {},
	-- armor
	Head = {},
	Torso = {},
	Legs = {},
}
Cuae_HeadTypes = {
	"LHead",
	"MHead",
	"HHead",
}
Cuae_TorsoTypes = {
	"LVest",
	"MVest",
	"HVest",
	"LPlate",
	"MPlate",
	"HPlate",
}
Cuae_LegsTypes = {
	"LLegs",
	"MLegs",
	"HLegs",
}
Cuae_AllArmor = {
	Head = {},
	Torso = {},
	Legs = {},
}

Cuae_AllGrenade = {}

Cuae_DefaultSmallWeapons = {
	Handgun = "HiPower",
	SMG = "UZI",
	FlareGun = "FlareHandgun",
	MeleeWeapon = "Knife",
}

Cuae_DefaultWeapons = {
	Rebel = {
		Handgun = "HiPower",
		SMG = "UZI",
		AssaultRifle = "AK47",
		Sniper = "DragunovSVD",
		Shotgun = "DoubleBarrelShotgun",
		MachineGun = "RPK74",
		FlareGun = "FlareHandgun",
		MeleeWeapon = "Knife",
		GrenadeLauncher = "MGL",
		Mortar = "MortarInventoryItem",
		MissileLauncher = "RPG7",
		Flare = "FlareStick",
		Explosive = "FragGrenade",
		Flash = "ConcussiveGrenade",
		Fire = "Molotov",
		Smoke = "SmokeGrenade",
		Tear = "TearGasGrenade",
		Toxic = "ToxicGasGrenade",
		Timed = "PipeBomb",
		Proximity = "ProximityTNT",
		Remote = "RemoteTNT",
	},
	Legion = {
		Handgun = "Bereta92",
		SMG = "MP5",
		AssaultRifle = "AK47",
		Sniper = "Gewehr98",
		Shotgun = "Auto5",
		MachineGun = "MG42",
		FlareGun = "FlareHandgun",
		MeleeWeapon = "Knife",
		GrenadeLauncher = "MGL",
		Mortar = "MortarInventoryItem",
		MissileLauncher = "RPG7",
		Flare = "FlareStick",
		Explosive = "FragGrenade",
		Flash = "ConcussiveGrenade",
		Fire = "Molotov",
		Smoke = "SmokeGrenade",
		Tear = "TearGasGrenade",
		Toxic = "ToxicGasGrenade",
		Timed = "PipeBomb",
		Proximity = "ProximityTNT",
		Remote = "RemoteTNT",
	},
	Thugs = {
		Handgun = "HiPower",
		SMG = "UZI",
		AssaultRifle = "AK47",
		Sniper = "DragunovSVD",
		Shotgun = "DoubleBarrelShotgun",
		MachineGun = "RPK74",
		FlareGun = "FlareHandgun",
		MeleeWeapon = "Knife",
		GrenadeLauncher = "MGL",
		Mortar = "MortarInventoryItem",
		MissileLauncher = "RPG7",
		Flare = "FlareStick",
		Explosive = "FragGrenade",
		Flash = "ConcussiveGrenade",
		Fire = "Molotov",
		Smoke = "SmokeGrenade",
		Tear = "TearGasGrenade",
		Toxic = "ToxicGasGrenade",
		Timed = "PipeBomb",
		Proximity = "ProximityTNT",
		Remote = "RemoteTNT",
	},
	Army = {
		Handgun = "Glock18",
		SMG = "MP5",
		AssaultRifle = "FNFAL",
		Sniper = "M24Sniper",
		Shotgun = "M41Shotgun",
		MachineGun = "FNMinimi",
		FlareGun = "FlareHandgun",
		MeleeWeapon = "Machete",
		GrenadeLauncher = "MGL",
		Mortar = "MortarInventoryItem",
		MissileLauncher = "RPG7",
		Flare = "FlareStick",
		Explosive = "FragGrenade",
		Flash = "ConcussiveGrenade",
		Fire = "Molotov",
		Smoke = "SmokeGrenade",
		Tear = "TearGasGrenade",
		Toxic = "ToxicGasGrenade",
		Timed = "TimedC4",
		Proximity = "ProximityC4",
		Remote = "RemoteC4",
	},
	Adonis = {
		Handgun = "ColtAnaconda",
		SMG = "MP5",
		AssaultRifle = "AR15",
		Sniper = "M24Sniper",
		Shotgun = "M41Shotgun",
		MachineGun = "HK21",
		FlareGun = "FlareHandgun",
		MeleeWeapon = "Knife_Sharpened",
		GrenadeLauncher = "MGL",
		Mortar = "MortarInventoryItem",
		MissileLauncher = "RPG7",
		Flare = "FlareStick",
		Explosive = "HE_Grenade",
		Flash = "ConcussiveGrenade",
		Fire = "Molotov",
		Smoke = "SmokeGrenade",
		Tear = "TearGasGrenade",
		Toxic = "ToxicGasGrenade",
		Timed = "TimedPETN",
		Proximity = "ProximityPETN",
		Remote = "RemotePETN",
	},
	SuperSoldiers = {
		Handgun = "Bereta92",
		SMG = "MP5",
		AssaultRifle = "FNFAL",
		Sniper = "M24Sniper",
		Shotgun = "M41Shotgun",
		MachineGun = "HK21",
		FlareGun = "FlareHandgun",
		MeleeWeapon = "Machete_Sharpened",
		GrenadeLauncher = "MGL",
		Mortar = "MortarInventoryItem",
		MissileLauncher = "RPG7",
		Flare = "FlareStick",
		Explosive = "HE_Grenade",
		Flash = "ConcussiveGrenade",
		Fire = "Molotov",
		Smoke = "SmokeGrenade",
		Tear = "TearGasGrenade",
		Toxic = "ToxicGasGrenade",
		Timed = "TimedC4",
		Proximity = "ProximityC4",
		Remote = "RemoteC4",
	},
	Militia = {
		Handgun = "HiPower",
		SMG = "UZI",
		AssaultRifle = "FAMAS",
		Sniper = "DragunovSVD",
		Shotgun = "Auto5",
		MachineGun = "RPK74",
		FlareGun = "FlareHandgun",
		MeleeWeapon = "Knife",
		GrenadeLauncher = "MGL",
		Mortar = "MortarInventoryItem",
		MissileLauncher = "RPG7",
		Flare = "FlareStick",
		Explosive = "FragGrenade",
		Flash = "ConcussiveGrenade",
		Fire = "Molotov",
		Smoke = "SmokeGrenade",
		Tear = "TearGasGrenade",
		Toxic = "ToxicGasGrenade",
		Timed = "TimedTNT",
		Proximity = "ProximityTNT",
		Remote = "RemoteTNT",
	},
}

CUAE_SLOT = {
	"Handheld A", -- 1
	"Handheld A", -- 2
	"Handheld B", -- 3
	"Handheld B", -- 4
}

-- Build when selecting ammunition of a caliber for a first time
Cuae_AllAmmunition = {}
